VendorCalc/force-app/main/default/objects/Calculator__c/Calculator__c.object-meta.xml
<CustomObject>
    <label>Chase Calculator Record</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chase Calculator Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Additional_Payment__c.field-meta.xml
<CustomField>
    <fullName>Additional_Payment__c</fullName>
    <label>Additional Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Amount_Financed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Financed__c</fullName>
    <label>Amount Financed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Ballon__c.field-meta.xml
<CustomField>
    <fullName>Ballon__c</fullName>
    <label>Ballon(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Balloon_c__c.field-meta.xml
<CustomField>
    <fullName>Balloon_c__c</fullName>
    <label>Balloon ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Cost_Price_Exc_GST__c.field-meta.xml
<CustomField>
    <fullName>Cost_Price_Exc_GST__c</fullName>
    <label>Cost Price Exc GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Cost_Price_Inc_GST__c.field-meta.xml
<CustomField>
    <fullName>Cost_Price_Inc_GST__c</fullName>
    <label>Cost Price Inc GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Customer_Rate_Expected__c.field-meta.xml
<CustomField>
    <fullName>Customer_Rate_Expected__c</fullName>
    <label>Customer Rate Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Customer_Rate_Non_Published__c.field-meta.xml
<CustomField>
    <fullName>Customer_Rate_Non_Published__c</fullName>
    <label>Customer Rate Non-Published</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Desired_Brokerage_Incl_GST_c__c.field-meta.xml
<CustomField>
    <fullName>Desired_Brokerage_Incl_GST_c__c</fullName>
    <label>Desired Brokerage Incl GST ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Desired_Brokerage_Incl_GST_p__c.field-meta.xml
<CustomField>
    <fullName>Desired_Brokerage_Incl_GST_p__c</fullName>
    <label>Desired Brokerage Incl GST (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Document_Fee_Disclosed__c.field-meta.xml
<CustomField>
    <fullName>Document_Fee_Disclosed__c</fullName>
    <label>Document Fee Disclosed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Document_Fee_Financed__c.field-meta.xml
<CustomField>
    <fullName>Document_Fee_Financed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Fee Financed</label>
    <type>Checkbox</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Establishment_Fee_Disclosed__c.field-meta.xml
<CustomField>
    <fullName>Establishment_Fee_Disclosed__c</fullName>
    <label>Establishment Fee Disclosed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Establishment_Fee_Financed__c.field-meta.xml
<CustomField>
    <fullName>Establishment_Fee_Financed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Establishment Fee Financed</label>
    <type>Checkbox</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Fee_Other_Financed__c.field-meta.xml
<CustomField>
    <fullName>Fee_Other_Financed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fee Other Financed</label>
    <type>Checkbox</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Fees_Other_Disclosed__c.field-meta.xml
<CustomField>
    <fullName>Fees_Other_Disclosed__c</fullName>
    <label>Fees Other Disclosed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Goods_Type__c.field-meta.xml
<CustomField>
    <fullName>Goods_Type__c</fullName>
    <label>Goods Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Incl_GST_c__c.field-meta.xml
<CustomField>
    <fullName>Incl_GST_c__c</fullName>
    <label>Incl GST ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/ITC_Level__c.field-meta.xml
<CustomField>
    <fullName>ITC_Level__c</fullName>
    <label>ITC Level</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Calculator_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Less_Deposite__c.field-meta.xml
<CustomField>
    <fullName>Less_Deposite__c</fullName>
    <label>Less Deposite</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Less_TradeIn__c.field-meta.xml
<CustomField>
    <fullName>Less_TradeIn__c</fullName>
    <label>Less TradeIn</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Loan_Facility_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Facility_Type__c</fullName>
    <label>Loan Facility Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Calculator_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Partner_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program__c</fullName>
    <label>Partner Program</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Payments_to_Own__c.field-meta.xml
<CustomField>
    <fullName>Payments_to_Own__c</fullName>
    <label>Payments to Own</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Please_enter_your_desired_Base_Rate_here__c.field-meta.xml
<CustomField>
    <fullName>Please_enter_your_desired_Base_Rate_here__c</fullName>
    <label>Please enter your desired Base Rate here</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/PPSR_Fee_Financed__c.field-meta.xml
<CustomField>
    <fullName>PPSR_Fee_Financed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PPSR Fee Financed</label>
    <type>Checkbox</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/PPSR_Fees_Disclosed__c.field-meta.xml
<CustomField>
    <fullName>PPSR_Fees_Disclosed__c</fullName>
    <label>PPSR Fees Disclosed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Principal_Amount__c.field-meta.xml
<CustomField>
    <fullName>Principal_Amount__c</fullName>
    <label>Principal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Program_Partner_L__c.field-meta.xml
<CustomField>
    <fullName>Program_Partner_L__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Partner</label>
    <referenceTo>Program_Partner__c</referenceTo>
    <relationshipName>Calculator_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Published_Base_Rate__c.field-meta.xml
<CustomField>
    <fullName>Published_Base_Rate__c</fullName>
    <label>Published Base Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Repayment_Expected_c__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Expected_c__c</fullName>
    <label>Repayment $ Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Repayment_Non_Published__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Non_Published__c</fullName>
    <label>Repayment $ Non-Published</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Term_months__c.field-meta.xml
<CustomField>
    <fullName>Term_months__c</fullName>
    <label>Term (months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Total_Incl_GST_c__c.field-meta.xml
<CustomField>
    <fullName>Total_Incl_GST_c__c</fullName>
    <label>Total (Incl GST) $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Total_Incl_GST_GST__c.field-meta.xml
<CustomField>
    <fullName>Total_Incl_GST_GST__c</fullName>
    <label>Total (Incl GST+GST) $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Calculator__c/fields/Unclaimable_GST__c.field-meta.xml
<CustomField>
    <fullName>Unclaimable_GST__c</fullName>
    <label>Unclaimable GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VendorCalc/force-app/main/default/objects/Program_Partner__c/Program_Partner__c.object-meta.xml
<CustomObject>
    <label>Chase Program Partner</label>
    <nameField>
        <label>Program Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chase Program Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VendorCalc/force-app/main/default/objects/Program_Partner__c/fields/Goods_Type__c.field-meta.xml
<CustomField>
    <fullName>Goods_Type__c</fullName>
    <inlineHelpText>Enter comma separated values. Eg: Telecommunications,Software</inlineHelpText>
    <label>Goods Type</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

VendorCalc/force-app/main/default/classes/MatrixGuestCalculatorController.cls
//This is the controller class for MatrixGuestCalculator Component
public class MatrixGuestCalculatorController {
    /*@AuraEnabled
    public static UserDetailsStatusWrapper authenticateUser_Apex(String userName, String password) {

        if(userName != null && password != null){
            UserDetailsStatusWrapper userDetailWrapper = new UserDetailsStatusWrapper();
            List<Matrix_Guest_User__c> matrixGuestUserList = new List<Matrix_Guest_User__c>();
            String status = '';
            matrixGuestUserList = [Select Id, Name, Password__c, Email__c, Username__c, Partner__c,Partner__r.Name, isActive__c from Matrix_Guest_User__c where Username__c =: userName and Password__c =: password limit 1];
            if(matrixGuestUserList.size() > 0){
                List<Program_Partner__c> prgramPartnerList = new List<Program_Partner__c>();
                prgramPartnerList = [Select Id, Active__c From Program_Partner__c Where Id =: matrixGuestUserList[0].Partner__c];
                userDetailWrapper.matrixUser = matrixGuestUserList[0];
                if(matrixGuestUserList[0].isActive__c && prgramPartnerList[0].Active__c){
                    userDetailWrapper.status = 'Active User';
                }else{
                    userDetailWrapper.status = 'InActive User';
                }
            }else{
                userDetailWrapper.status = 'Invalid User';
            }
            return userDetailWrapper;
        }
        return null;
    }

    @AuraEnabled
    public static leadCalculatorWrapper getRelatedRecords_Apex(String program) {

        if(program != null){
            List<Lead> leadList = new List<Lead>();
            leadCalculatorWrapper leadcalcWrapper = new leadCalculatorWrapper();
            List<Calculator__c> calculatorRecordList = new List<Calculator__c>();
            Id RecordTypeId = Schema.SObjectType.Calculator__c.getRecordTypeInfosByName().get('Supplier Quote').getRecordTypeId();

            calculatorRecordList = [SELECT
            Id,
            Name,
            Additional_Payment__c,
            Additional_period__c,
            Amount_Financed__c,
            Ballon__c,
            Balloon_c__c,
            customer_Rate_Expected__c,
            customer_Rate_Non_Published__c,
            Date__c,
            Desired_Brokerage_Incl_GST_c__c,
            Desired_Brokerage_Incl_GST_p__c,
            Document_Fee_Disclosed__c,
            Fees_Other_Disclosed__c,
            Goods_Type__c,
            Incl_GST_c__c,
            Lead__c,
            Loan_Facility_Type__c,
            Opportunity__c,
            Please_enter_your_desired_Base_Rate_here__c,
            PPSR_Fees_Disclosed__c,
            Published_Base_Rate__c,
            Repayment_Expected_c__c,
            Repayment_Non_Published__c,
            Repayment_Frequency__c,
            Repayment_Type__c,
            State__c,
            Term_months__c,
            Document_Fee_Financed__c,
            PPSR_Fee_Financed__c,
            Fee_Other_Financed__c,
            ITC_Level__c,
            Total_Incl_GST_GST__c,
            Unclaimable_GST__c,
            GST__c,
            Establishment_Fee_Disclosed__c,
            Establishment_Fee_Financed__c,
            Cost_Price_Exc_GST__c,
            Cost_Price_Inc_GST__c,
            Less_Deposite__c,
            Less_TradeIn__c,
            Principal_Amount__c,
            Total_Incl_GST_c__c,
            Email_Address__c,
            Phone__c,
            Partner_Program__c,
            Program_Partner_L__c,
            Position__c,
            Company_Name__c,
            Payments_to_Own__c
            FROM Calculator__c
            WHERE Program_Partner_L__c = :program and RecordTypeId =: RecordTypeId and Lead__c != ''];

            if(calculatorRecordList.size() > 0){
                Id RecId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('MFG Vendor').getRecordTypeId();
                Set<Id> calcRecordSet = new Set<Id>();
                for(Calculator__c calcObj : calculatorRecordList){
                    calcRecordSet.add(calcObj.Lead__c);
                }
                if(calcRecordSet.size() > 0){
                    leadList = [Select Id, Name,Company, Amount_Financed__c, Date__c, Status, Email, Phone,OwnerId,Matrix_Guest_User__r.Username__c,Matrix_Guest_User__r.Name, Term__c  from Lead where Id in: calcRecordSet and  RecordTypeId =: RecId and Matrix_Guest_User__c != '' ORDER BY CreatedDate DESC];
                }
            }
            leadcalcWrapper.leadList = leadList;
            leadcalcWrapper.calcList = calculatorRecordList;
            
            return leadcalcWrapper;
        }
        return null;
    }

    public class UserDetailsStatusWrapper{
        @AuraEnabled public Matrix_Guest_User__c matrixUser{get;set;}
        @AuraEnabled public String status{get;set;}
    }

    public class leadCalculatorWrapper{
        @AuraEnabled public List<Lead> leadList{get;set;}
        @AuraEnabled public List<Calculator__c> calcList{get;set;}
    }*/
}